/** Workflow Governance — 月度探索推荐、chaos 必须留 trace */
export const WORKFLOW_GOVERNANCE = {
  MONTHLY_EXPLORE_RECOMMENDATION_REQUIRED: true,
  MONTHLY_UNEXPLORED_PATH_REPORT_REQUIRED: true,
  CHAOS_REQUIRES_TRACE_SUMMARY: true,
  IGNORE_REQUIRES_EXPLICIT_ACKNOWLEDGEMENT: true,
  RESOLVER_CORE_TRACE_REQUIRED: true,
  REPLAY_PREFERS_RECORDED_PARAMS: true,
} as const;
